services:
  stock-checker:
    build: .
    container_name: nvidia-stock-checker
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - STOCK_CHECK_INTERVAL=${STOCK_CHECK_INTERVAL:-60}
      - NVIDIA_SKU=${NVIDIA_SKU:-NVGFT580}
      - NVIDIA_LOCALE=${NVIDIA_LOCALE:-es-es}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped